### ISSUE TITLE
MakeBadgeForTabAt more than four are bugs

### ISSUE THREAD

**Issue by zhanaotian** [roughike/BottomBar#357] opened 2016-07-14 02:34 UTC
![bottombar](https://cloud.githubusercontent.com/assets/6057569/16825719/a9f0bfd4-49a9-11e6-8289-041588ce7bb8.png)

        redColor = Color.parseColor("#FF0000");
        BottomBarBadge nearbyBadge = mBottomBar.makeBadgeForTabAt(0, redColor, 5);
        BottomBarBadge nearbyBadge1 = mBottomBar.makeBadgeForTabAt(1, redColor, 5);
        BottomBarBadge nearbyBadge2 = mBottomBar.makeBadgeForTabAt(2, redColor, 5);
        BottomBarBadge nearbyBadge3 = mBottomBar.makeBadgeForTabAt(3, redColor, 5);
        BottomBarBadge nearbyBadge4 = mBottomBar.makeBadgeForTabAt(4, redColor, 5);

        nearbyBadge.setAutoShowAfterUnSelection(true);
        nearbyBadge1.setAutoShowAfterUnSelection(true);
        nearbyBadge2.setAutoShowAfterUnSelection(true);
        nearbyBadge3.setAutoShowAfterUnSelection(true);
        nearbyBadge4.setAutoShowAfterUnSelection(true);

**Comment by iHandy** [comment] 2016-07-18 16:06
Also reproduced if adding badge to current selected tab. It seems, that incorrect place (size) calculation in BottomBarBadge constructor.

**Comment by roughike** [comment] 2016-08-31 19:35
Should've been fixed in the 2.0.2 version.

**Closed by roughike** 2016-08-31 19:35 UTC

**Comment by serenasoldo** [comment] 2016-09-21 14:24
fyi, I'm using version 2.0.2 and I still experience this issue sometimes (I can't reproduce it systematically, though).
