### ISSUE TITLE
set five tabs without titles

### ISSUE THREAD

**Issue by sarang1996** [roughike/BottomBar#488] opened 2016-09-08 09:55 UTC
@roughike i want to implement tabs without titles but it gives me white space when title is shown, i want to remove it. help!

**Comment by josefkorbel** [comment] 2016-09-08 13:35
#424

**Comment by roughike** [comment] 2017-03-26 13:25
A duplicate of #373, so closing this one.

Expect to see this with the next release.

**Closed by roughike** 2017-03-26 13:25 UTC
Labels: duplicate
