### ISSUE TITLE
Not showing titles

### ISSUE THREAD

**Issue by IvanSyabro** [roughike/BottomBar#531] opened 2016-10-05 16:00 UTC
![9b3c3c0a23](https://cloud.githubusercontent.com/assets/20424848/19121121/f7257cb6-8b2d-11e6-8232-b2ea9d4a715b.jpg)

**Comment by IvanSyabro** [comment] 2016-10-05 16:01
Device: Nexus 5x, API 24 (Android 7.0)

**Comment by timrijckaert** [comment] 2016-10-05 20:25
Same problem here. Nexus 6P Android 7.0

**Comment by timrijckaert** [comment] 2016-10-05 20:49
Possible duplicate of #474

**Comment by elaman16** [comment] 2016-10-06 04:41
Like rickytribbi,
Works also for me checking out both paddings = 0 in Android asset studio generator!

**Comment by timrijckaert** [comment] 2016-10-06 09:07
Using the site it indeeds works. But since Android Studio has a drawable importer it would be nice that it would play along with that one.

**Comment by KirillMakarov** [comment] 2016-10-06 11:35
Same in #530

**Comment by zhaoyou** [comment] 2016-10-19 08:47
I work for me. use Android asset studio generator

![screen shot 2016-10-19 at 4 45 28 pm](https://cloud.githubusercontent.com/assets/612257/19511816/9290823e-961b-11e6-908c-3a300a1ce4d6.png)

**Comment by silviahisham** [comment] 2016-11-14 10:25
same problem

**Comment by zbrook** [comment] 2016-11-16 07:25
This advice worked to allow an image asset created from Android Studio to work:
https://github.com/roughike/BottomBar/issues/474#issuecomment-256051845

> When adding an Image Asset to your Drawable folder, chose Notification Icons instead of the regular Action Bar and Tab Icons - worked fine !

**Comment by roughike** [comment] 2017-04-06 18:23
Should be fixed in latest versions.

**Closed by roughike** 2017-04-06 18:23 UTC
