### ISSUE TITLE
Bottombar overlaps FAB

### ISSUE THREAD

**Issue by mediendev** [roughike/BottomBar#310] opened 2016-06-22 17:04 UTC
Tried all combinations from issues....but bottom bar overlays FAB. using 1.3.9
 mBottomBar = BottomBar.attachShy((CoordinatorLayout) findViewById(R.id.base_coordinator_layout),
               findViewById(R.id.base_fragment_container), savedInstanceState);
       mBottomBar.noNavBarGoodness();
       mBottomBar.noTopOffset();
       mBottomBar.noTabletGoodness();
       mBottomBar.noResizeGoodness();
       mBottomBar.setItems(
               new BottomBarTab(R.drawable.ic_assignment_white_24dp, "Recents"),
               new BottomBarTab(R.drawable.ic_library_books_white_24dp, "Favorites"),
               new BottomBarTab(R.drawable.ic_account_box_white_24dp, "Nearby")
       );

Here is the layout

<android.support.v4.widget.DrawerLayout
    android:id="@+id/base_drawer_layout"
    android:layout_width="match_parent"
    android:layout_height="match_parent"
    xmlns:android="http://schemas.android.com/apk/res/android"
    xmlns:app="http://schemas.android.com/apk/res-auto">

    <android.support.design.widget.CoordinatorLayout
        android:id="@+id/base_coordinator_layout"
        android:layout_width="match_parent"
        android:layout_height="match_parent"
        android:fitsSystemWindows="true"
        >

        <android.support.design.widget.AppBarLayout
            android:layout_width="match_parent"
            android:layout_height="wrap_content"
            >

            <android.support.v7.widget.Toolbar
                android:id="@+id/base_toolBar"
                android:layout_width="match_parent"
                android:layout_height="?actionBarSize"          
                app:theme="@style/ToolBarStyle"
                android:title="Title"  />

        </android.support.design.widget.AppBarLayout>

        <FrameLayout
            android:id="@+id/base_fragment_container"
            android:layout_width="match_parent"
            android:layout_height="match_parent"            
            app:layout_behavior="@string/appbar_scrolling_view_behavior"
            />

        <android.support.design.widget.FloatingActionButton
            android:id="@+id/fab"
            android:layout_width="wrap_content"
            android:layout_height="wrap_content"
            android:layout_margin="@dimen/fab_margin"            
            android:src="@drawable/ic_add_white_18dp"
            android:layout_gravity="bottom|end"/>
    </android.support.design.widget.CoordinatorLayout>

    <android.support.design.widget.NavigationView
        android:id="@+id/navigationView"
        android:layout_width="wrap_content"
         android:layout_height="match_parent"
        android:layout_gravity="start"
        app:itemIconTint="@color/nav_drawer_row_icon"
        app:itemTextColor="@color/menu_text_color_state"
        app:menu="@menu/menu_drawer" />
</android.support.v4.widget.DrawerLayout>

**Comment by alvarlagerlof** [comment] 2016-06-25 20:31
Have the exact same problem. Ended up with a fixed bottombar

` mBottomBar = BottomBar.attach(this, savedInstanceState);`

**Comment by wimbervoets** [comment] 2016-06-29 12:10
Same issue here. This is regression compared to the previous version I used (= 1.3.4).
I also switched back to the fixed bottombar, but in that case it overlaps my material drawer...

**Comment by alvarlagerlof** [comment] 2016-06-29 20:50
@wimbervoets Yeah mine goes over my drawer to. I wanted to attach it to my coordinatorlayout but it didn't work

**Comment by roughike** [comment] 2016-08-31 19:34
Should've been fixed in 2.0 and up, since the BottomBar is just a regular View now.

**Closed by roughike** 2016-08-31 19:34 UTC
