### ISSUE TITLE
`IllegalArgumentException: Wrong state class` when call `Activity.recreate()`

### ISSUE THREAD

**Issue by Kevinrob** [roughike/BottomBar#445] opened 2016-08-26 13:01 UTC
> Caused by: java.lang.IllegalArgumentException: Wrong state class, expecting View State but received class android.os.Bundle instead. This usually happens when two views of different type have the same id in the same hierarchy. This view's id is id/bottomBarFlux. Make sure other views do not use the same id.
> at android.view.View.onRestoreInstanceState(View.java:15659)
> at com.roughike.bottombar.BottomBarTab.onRestoreInstanceState(BottomBarTab.java:453)

**Comment by Kevinrob** [comment] 2016-08-26 13:03
In `BottomBarTab.java`
```java
@Override
    public void onRestoreInstanceState(Parcelable state) {
        if (badge != null && state instanceof Bundle) {
            Bundle bundle = (Bundle) state;
            badge.restoreState(bundle, indexInContainer);

            state = bundle.getParcelable("superstate");
        }
        super.onRestoreInstanceState(state);
    }
```

=> `if (badge != null && state instanceof Bundle)` will never be `true`  
Must be `if(state instanceof Bundle)` and `badge` must be init in the `if`, no?

**Comment by roughike** [comment] 2016-08-27 07:17
Can you provide more details how did you encounter this issue?

**Comment by Kevinrob** [comment] 2016-08-29 06:11
I will create a test application soon.

**Comment by Kevinrob** [comment] 2016-08-30 06:55
@roughike I made a test app project https://github.com/Kevinrob/bottom-bar-test
The APK for testing without build => https://github.com/Kevinrob/bottom-bar-test/raw/master/TestApp/app-debug.apk

**_Just click first button and second_** => crash :bomb: 

The problem is that when a view is restored, a new instance of the class is created... We have to re-create the `badge` object if needed. :smiley:

**Comment by brianhama** [comment] 2016-08-31 09:01
We are also running into this issue in a production app, Nearby Live.

**Comment by roughike** [comment] 2016-08-31 17:15
This is now fixed and will be released in the v2.0.3 version during the weekend. This was due to the fact that the ```super.onRestoreInstanceState()``` method expects a View state (Parcelable), but received the Bundle we're storing our custom state data. The fix was to get that Parcelable out of the custom Bundle and pass that instead.

Huge thanks to @Kevinrob for reporting and helping to reproduce the issue!

**Closed by roughike** 2016-08-31 17:15 UTC
Labels: bug, v2

**Comment by Kevinrob** [comment] 2016-08-31 18:02
Good news! Glad to read that. Thanks

**Comment by Kevinrob** [comment] 2016-09-06 06:02
@roughike Sorry for asking that, but what about the `v2.0.3` release? :smile: 
I'd love to use it instead of my temporary forked repository

**Comment by nmoskalenko** [comment] 2016-09-28 05:03
@roughike, can you please release the version with this fix? My app is crashing :)

**Comment by flashfabrixx** [comment] 2016-10-10 10:44
Would be great to have this fix in a new release soon!

**Comment by Kevinrob** [comment] 2016-10-17 06:04
@roughike any update? Do you need help on something?

**Comment by ameyab10** [comment] 2016-11-04 23:15
@roughike Since its already fixed can we have a .release for this?

**Comment by Kevinrob** [comment] 2017-01-16 07:13
Thank you @roughike for publishing `2.1.0` with this fix! https://bintray.com/roughike/maven/bottom-bar/2.1.0
