### ISSUE TITLE
Tab title stuck when tab has Badge

### ISSUE THREAD

**Issue by Odaym** [roughike/BottomBar#139] opened 2016-04-07 10:54 UTC
Everything works fine until I set a badge on the very last tab to the right (at the edge of the screen), and I press on the tab, the badge disappears normally but when I navigate away, the tab title is stuck still open while the tab has closed. Attached screenshot here: [http://imgur.com/wDZwf1B](http://imgur.com/wDZwf1B)

Great job by the way

**Comment by roughike** [comment] 2016-04-07 11:24
Are you using the latest version?

**Comment by Odaym** [comment] 2016-04-07 11:25
1.3.1

**Comment by roughike** [comment] 2016-04-07 12:50
I'll investigate.

**Comment by roughike** [comment] 2016-04-07 13:02
I can't replicate the issue.

Can you provide some Java code that makes the bug happen?

**Comment by Odaym** [comment] 2016-04-07 13:11
[http://pastie.org/10788761](http://pastie.org/10788761)

**Comment by NickM-27** [comment] 2016-04-08 02:48
I also have an issue sort of similar to this, when I call selectTabAtPosition(); the tab gets selected but all the other icons don't shift so it creates an incorrect effect

**Comment by bpappin** [comment] 2016-04-26 16:33
these appear to all be related: #178 #143 #139

**Comment by bpappin** [comment] 2016-04-26 16:39
I can confirm. As soon as I add badges, the tabs stop responding properly.

**Comment by SpinyLei** [comment] 2016-05-04 08:04
The bug is the 'handleClick' method of class 'BottomBar'

replace 
`
if (v.getTag().equals(TAG_BOTTOM_BAR_VIEW_INACTIVE)) {
            while (null!=findViewWithTag(TAG_BOTTOM_BAR_VIEW_ACTIVE)){
                View oldTab = findViewWithTag(TAG_BOTTOM_BAR_VIEW_ACTIVE);

                unselectTab(oldTab, true);

                shiftingMagic(oldTab, v, true);
            }
            selectTab(v, true);

        }
`
instead of 
`
 if (v.getTag().equals(TAG_BOTTOM_BAR_VIEW_INACTIVE)) {
            View oldTab = findViewWithTag(TAG_BOTTOM_BAR_VIEW_ACTIVE);

            unselectTab(oldTab, true);
            selectTab(v, true);

            shiftingMagic(oldTab, v, true);
        }
`
in 1022 line

**Comment by Odaym** [comment] 2016-05-04 08:39
you gonna submit a PR?

**Comment by bmarty** [comment] 2016-05-10 14:07
Hi,
I'm also observing issue when adding a badge to a tab element. (Nexus 4 with 4 tab)
Strangely, after rotating the screen to landscape, the issue is not observed, and if rotating back to portrait, the issue is not observed any more!
BR

**Comment by bmarty** [comment] 2016-06-08 15:14
It seems to be fixed on version 1.3.7 ;-)

**Closed** 2016-06-08 16:29 UTC
Labels: bug
