### ISSUE TITLE
Disable Text Under Icons

### ISSUE THREAD

**Issue by josefkorbel** [roughike/BottomBar#424] opened 2016-08-22 15:42 UTC
Hello guys, can anyone tell me how to set bottombar to "only icon mode" ? I have the icons moved up, like the text was there, but i want to use only icons, having empty text there is not enought for it apparently, thanks in advance !

**Comment by sayoojvalsan-demandmedia** [comment] 2016-08-22 18:46
I have the same issue.

**Comment by Mayur-007** [comment] 2016-08-24 14:45
same problem..

**Comment by alizarei95** [comment] 2016-09-06 04:30
same for me

**Comment by oradkovsky** [comment] 2016-09-07 14:32
Actually this library does support icon-only mode, though may be it's not straightforward. If you look into code, you'll notice that TextView's style (your label below icon) is: BB_BottomBarItem_TitleStyle (do not mix with text appearance - that's different). So you can override it like this:

`    <style name="BB_BottomBarItem_TitleStyle" parent="BB_BottomBarItem_TitleStyle">
        <item name="android:visibility">gone</item>
    </style>`

One last bit to do is to change container gravity (container is what hosts tab views like imageview, textview etc)

`        for (int i = 0; i < mBottomBar.getTabCount(); i++) {
            mBottomBar.getTabAtPosition(i).setGravity(Gravity.CENTER_VERTICAL);
        }`

The above works for default BottomBar settings (likely for other settings as well, but I wasn't testing).

**Comment by josefkorbel** [comment] 2016-09-08 12:24
Wow, it actully work somehow, thanks @oradkovsky

**Comment by akrupych-remit** [comment] 2016-10-10 09:56
@roughike Please set the gravity to "center" in tab layouts

**Comment by liovincis** [comment] 2016-10-19 17:18
Ok that seems to work, but the problem is now the icons are too small, is there a way to increase the icon size since there is more space available with the text removed?

**Comment by Shamsul1** [comment] 2016-11-21 06:30
my issue is total opposite. i don't see any text under icons.

**Comment by sagarc91** [comment] 2017-03-23 13:04
app:bb_titleTextAppearance="@dimen/bottom_text"

just override this with bottom_text=0dp

**Comment by roughike** [comment] 2017-03-26 13:25
A duplicate of #373, so closing this one.

Expect to see this with the next release.

**Closed by roughike** 2017-03-26 13:25 UTC
Labels: duplicate, enhancement
