### ISSUE TITLE
space left if title not given

### ISSUE THREAD

**Issue by BishalSaha** [roughike/BottomBar#694] opened 2017-03-17 14:22 UTC
space is left under the icons if name not given

**Comment by satti8893** [comment] 2017-03-22 06:10
Check this out : https://github.com/roughike/BottomBar/issues/655

**Comment by roughike** [comment] 2017-03-26 13:28
A duplicate of #373, so closing this one.

Expect to see this with the next release.

**Closed by roughike** 2017-03-26 13:28 UTC
Labels: duplicate
