### ISSUE TITLE
Bottom bar items with no title have extra space

### ISSUE THREAD

**Issue by Dimezis** [roughike/BottomBar#635] opened 2017-01-27 12:03 UTC
If I remove item titles at all, there's still an empty space below icons, no matter which bottom bar size I specify.
![image](https://cloud.githubusercontent.com/assets/1433500/22370274/f367c752-e490-11e6-801e-79288eda3291.png)

**Comment by Singwai** [comment] 2017-01-27 22:18
https://github.com/roughike/BottomBar/pull/636

**Comment by Dimezis** [comment] 2017-01-29 14:17
@Singwai isn't it simpler to do a check `TextUtils.isEmpty(title)` and set visibility of the title based on that, instead of introducing new attribute?

**Comment by Singwai** [comment] 2017-01-30 16:23
hmm good call... but I was thinking to have this configuration expose in the BottomBar instead of the xml in the tab. In addition, there are already similar configs exposed in the BottomBar, such as `bb_titleTextAppearance` and `bb_titleTypeFace` . I think this will keep the style more consistent with the current code style.

**Comment by abc873693** [comment] 2017-02-02 13:45
I use `setPadding()` to finish this . Remember setting title to empty.
Example:
`bottomBar.getTabWithId(R.id.tab_roomType).setPadding(0,PaddingTop,0,0);`

**Comment by huzyrah** [comment] 2017-02-27 12:10
abc873693 how do you do that? can you explain in detail? I really need to remove the title below the icons and make them positioned at center.

**Comment by huzyrah** [comment] 2017-02-27 12:11
@abc873693 how do you do that? can you explain in detail? I really need to remove the title below the icons and make them positioned at center.

**Comment by abc873693** [comment] 2017-02-27 14:22
@huzyrah  in programming. BottomBar 's function getTabWithId(int) can get BottomBar item , then use setPadding() let PaddingTop to title disappear.

**Comment by huzyrah** [comment] 2017-02-27 15:29
@abc873693 in which file and in which line should i insert that code? sorry, I'm still a noob at this :'(

**Comment by abc873693** [comment] 2017-02-27 15:35
@huzyrah in java file. you can set this after initial view.

**Comment by huzyrah** [comment] 2017-02-27 15:39
@abc873693 ohh...is it in the `BottomBarTab.java` or just the `BottomBar.java` ?

**Comment by abc873693** [comment] 2017-02-27 15:44
@abc873693 in use BottomBar place . ex MainActivity

**Comment by huzyrah** [comment] 2017-02-27 15:46
@abc873693 do you mind sending me your edited code or solution? I can't seem to fix the issue just yet. My email is huzyrah@gmail.com

**Comment by abc873693** [comment] 2017-02-27 19:26
@huzyrah this project is sample for de title method. 
https://github.com/abc873693/BottomBardetitle
or you can extend BottomBar.java to edit isvisble

**Comment by huzyrah** [comment] 2017-02-27 23:41
@abc873693 ohh, I get it now. thanks, mate! :)

**Comment by huzyrah** [comment] 2017-02-27 23:45
@abc873693 oh, I get it now. thank you for the code given. but is there a way to make the top padding and bottom padding of the icons equal? Because mine has more white space on top of each icons.
![issue](https://cloud.githubusercontent.com/assets/26061356/23385267/d4dea55a-fd89-11e6-812f-06b7158fc3cc.png)
.

**Comment by abc873693** [comment] 2017-02-28 03:59
@huzyrah  set bottombar 's height

**Comment by roughike** [comment] 2017-03-26 13:27
A duplicate of #373, so closing this one.

Expect to see this with the next release.

**Closed by roughike** 2017-03-26 13:27 UTC
Labels: duplicate
