### ISSUE TITLE
How can i disable title or text below icons.

### ISSUE THREAD

**Issue by debjitk** [roughike/BottomBar#655] opened 2017-02-14 13:29 UTC
I don't want to show text with icons in bottom bar ? How do i accomplish the same ?

**Comment by avivcaspi** [comment] 2017-02-18 11:28
maybe try to put " " in the title field of the bottombar xml

**Comment by debjitk** [comment] 2017-02-18 16:40
I have tried the same. In that case the icons is getting vertically aligned.

**Comment by thatrun** [comment] 2017-02-20 17:38
Do you have a right answer? I want to implement the same thing.

**Comment by ChaosLeong** [comment] 2017-02-21 09:11
There is a trick.

``` Java
for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);

    View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
    BottomBarTab.LayoutParams params = (BottomBarTab.LayoutParams) icon.getLayoutParams();
    params.gravity = Gravity.CENTER;
    icon.setLayoutParams(params);
    // the paddingTop will be modified when select/deselect,
    // so, in order to make the icon always center in tab,
    // we need set the paddingBottom equals paddingTop
    icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

    View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
    title.setVisibility(View.GONE);
}
```

**Comment by huzyrah** [comment] 2017-02-27 12:10
@ChaosLeong how do you do that? can you explain in detail? I really need to remove the title below the icons and make them positioned at center.

**Comment by ChaosLeong** [comment] 2017-02-27 14:51
@huzyrah By reading [bb_bottom_bar_item_fixed.xml](https://github.com/roughike/BottomBar/blob/338ee864392087f0233ef42765730e00810cd020/bottom-bar/src/main/res/layout/bb_bottom_bar_item_fixed.xml), we known the `<merge />` element as the root view and the icon has `paddingTop`(with 8dp).

Find that the `bb_bottom_bar_item_fixed.xml` usages in the [BottomBarTab#L118](https://github.com/roughike/BottomBar/blob/338ee864392087f0233ef42765730e00810cd020/bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java#L118). And the [BottomBarTab](https://github.com/roughike/BottomBar/blob/338ee864392087f0233ef42765730e00810cd020/bottom-bar/src/main/java/com/roughike/bottombar/BottomBarTab.java#L38) extends from LinearLayout.

So, if you want to move the icon at center, just change the `layout_gravity` attribute of the BottomBarTab to `center`, make the `paddingTop` of icon equals to `paddingBottom`, and hide the title. There is the magic. ：P 

I'm not sure the above explanation can make you understand. ~~Because my English is not good.~~ Hope it help for you.：）

**Comment by huzyrah** [comment] 2017-02-27 15:14
so does that mean I have to insert the following code to the bb_bottom_bar_item_fixed.xml ? or where do I put it eaxctly? in which file? sorry, i'm still a noob at this :'(
`for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);

    View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
    // the paddingTop will be modified when select/deselect,
    // so, in order to make the icon always center in tab,
    // we need set the paddingBottom equals paddingTop
    icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

    View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
    title.setVisibility(View.GONE);
}`

**Comment by huzyrah** [comment] 2017-02-27 15:15
so does that mean I have to insert the following code to the bb_bottom_bar_item_fixed.xml ? or where do I put it eaxctly? in which file? sorry, i'm still a noob at this :'(

`
for (int i = 0; i < mBottomBar.getTabCount(); i++) {
BottomBarTab tab = mBottomBar.getTabAtPosition(i);
tab.setGravity(Gravity.CENTER);

View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
// the paddingTop will be modified when select/deselect,
// so, in order to make the icon always center in tab,
// we need set the paddingBottom equals paddingTop
icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
title.setVisibility(View.GONE);
}
`

**Comment by huzyrah** [comment] 2017-02-27 15:16
so does that mean I have to insert the following code to the bb_bottom_bar_item_fixed.xml ? or where do I put it eaxctly? in which file? sorry, i'm still a noob at this :'(

`for (int i = 0; i < mBottomBar.getTabCount(); i++) {
BottomBarTab tab = mBottomBar.getTabAtPosition(i);
tab.setGravity(Gravity.CENTER);

View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
// the paddingTop will be modified when select/deselect,
// so, in order to make the icon always center in tab,
// we need set the paddingBottom equals paddingTop
icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
title.setVisibility(View.GONE);
}`

**Comment by huzyrah** [comment] 2017-02-27 15:18
@ChaosLeong so does that mean I have to insert the following code to the bb_bottom_bar_item_fixed.xml ? or where do I put it eaxctly? in which file? sorry, i'm still a noob at this :'(

`for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);

    View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
    // the paddingTop will be modified when select/deselect,
    // so, in order to make the icon always center in tab,
    // we need set the paddingBottom equals paddingTop
    icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

    View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
    title.setVisibility(View.GONE);
}`

**Comment by huzyrah** [comment] 2017-02-27 15:27
@ChaosLeong so does that mean I have to insert the following code to the `BottomBarTab.java` ? or where do I put it eaxctly? in which line and in which file? sorry, i'm still a noob at this :'(

`   for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);

    View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
    // the paddingTop will be modified when select/deselect,
    // so, in order to make the icon always center in tab,
    // we need set the paddingBottom equals paddingTop
    icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

    View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
    title.setVisibility(View.GONE);
    }`

**Comment by huzyrah** [comment] 2017-02-27 15:30
`for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);`

**Comment by huzyrah** [comment] 2017-02-27 15:31
`for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);`

`for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);`

**Comment by huzyrah** [comment] 2017-02-27 15:31
for (int i = 0; i < mBottomBar.getTabCount(); i++) {
    BottomBarTab tab = mBottomBar.getTabAtPosition(i);
    tab.setGravity(Gravity.CENTER);

    View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
    // the paddingTop will be modified when select/deselect,
    // so, in order to make the icon always center in tab,
    // we need set the paddingBottom equals paddingTop
    icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

    View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
    title.setVisibility(View.GONE);
}``

**Comment by huzyrah** [comment] 2017-02-27 15:42
@ChaosLeong do you mind emailing me your edited code or solution? I can't seem to fix the issue just yet.

**Comment by huzyrah** [comment] 2017-02-27 15:44
@ChaosLeong do you mind sending me your edited code or solution? I can't seem to fix the issue just yet. I have emailed you about this earlier.

**Comment by ChaosLeong** [comment] 2017-02-27 16:01
@huzyrah Sorry to check your e-mail so late.

Place the code after the initialization code of BottomBar.


```
public class MainActivity extends AppCompatActivity {

    private BottomBar mBottomBar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main_content);

        // setup your BottomBar here
        setupBottomBar();

        for (int i = 0; i < mBottomBar.getTabCount(); i++) {
            BottomBarTab tab = mBottomBar.getTabAtPosition(i);
            tab.setGravity(Gravity.CENTER);

            View icon = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_icon);
            // the paddingTop will be modified when select/deselect,
            // so, in order to make the icon always center in tab,
            // we need set the paddingBottom equals paddingTop
            icon.setPadding(0, icon.getPaddingTop(), 0, icon.getPaddingTop());

            View title = tab.findViewById(com.roughike.bottombar.R.id.bb_bottom_bar_title);
            title.setVisibility(View.GONE);
        }
    }
}
```

**Comment by huzyrah** [comment] 2017-02-27 23:25
@ChaosLeong I have an error on the `setupBottomBar( );` line. Also, the first line of my code on `MainActivity.java` is quite different from yours because mine is `public class MainActivity extends AppCompatActivity implements View.OnClickListener {` and yours doesn't have the ` implements View.OnClickListener` . Is yours edited or the original one?

Below is the screenshot of what I did to the `MainActivity. java` . I tried to follow your codes but somehow it still has error. 
![issue](https://cloud.githubusercontent.com/assets/26061356/23384666/fd658b4a-fd86-11e6-9089-1700d6f5e85a.png)

**Comment by ChaosLeong** [comment] 2017-02-28 01:30
Check the code here https://gist.github.com/ChaosLeong/e940f865dd81550c540eb0c0d94824b1.

**Comment by huzyrah** [comment] 2017-02-28 22:47
@ChaosLeong please check your email. I just emailed you a new folder last night.

**Comment by roughike** [comment] 2017-03-26 13:27
A duplicate of #373, so closing this one.

Expect to see this with the next release.

**Closed by roughike** 2017-03-26 13:27 UTC
Labels: duplicate

**Comment by LaurieScheepers** [comment] 2017-05-18 10:50
Is this functionality in the current release (2.3.1)? If so, how do I remove the titles?

**Comment by Schinizer** [comment] 2017-08-01 07:44
For a single tab title to be disabled, use `iconOnly="true"` as follows
```
<tab
        id="@+id/item"
        icon="@drawable/something"
        iconOnly="true"/>
```
For icon only mode for the entire bottombar, use `app:bb_behavior="iconsOnly"` instead
```
<com.roughike.bottombar.BottomBar
        android:id="@+id/bottomBar"
        android:layout_width="match_parent"
        android:layout_height="56dp"
        android:layout_gravity="bottom"
        app:bb_tabXmlResource="@xml/bottombar_tabs"
        app:bb_behavior="iconsOnly"/>
```
