### ISSUE TITLE
Remove title below each icons and remove the white space below them

### ISSUE THREAD

**Issue by huzyrah** [roughike/BottomBar#668] opened 2017-02-27 12:24 UTC
Can someone help me how to remove the title below each icon in every of the bottom navigation bar? I only need the icons without the title, just like the one in Instagram. I did try changing the title to "" (empty string). However, the icon is not centered. There is still a white space below each icon. Can anyone help me? I'm still a newbie. :'(
![issue](https://cloud.githubusercontent.com/assets/26061356/23361308/ff0c3cca-fd2a-11e6-92ea-9b71c0852aa0.png)

**Comment by YARSN** [comment] 2017-02-27 14:06
Take a look at [#655](https://github.com/roughike/BottomBar/issues/655), maybe this help you.

**Comment by huzyrah** [comment] 2017-02-27 15:29
@YARSN oh...thanks, mate!

**Comment by roughike** [comment] 2017-03-26 13:28
A duplicate of #373, so closing this one.

Expect to see this with the next release.

**Closed by roughike** 2017-03-26 13:28 UTC
Labels: duplicate
